pipeline {
    agent {
        node {
            label "terraform"
        }
    }

    stages {
        // ********************************
        // *** Validate Terraform files ***
        // ********************************
        stage("Terraform Validate") {
            steps{
                echo "**** Validating ****"
                sh 'bash bin/validate.sh'
            }
        }

        // ****************************
        // *** Plan Terraform files ***
        // ****************************
        stage("Terraform Plan") {
            steps{
                echo "**** Planning ****"
                sh 'bash bin/plan.sh'
            }
        }

        // *****************************
        // *** Apply Terraform files ***
        // *****************************
        stage("Terraform Apply") {
            when {
                branch "master-rc"
            }
            steps{
                echo "**** Apply ****"
                sh 'bash bin/apply.sh'
            }
        }
    }

    post {
        success {
            script {
                if (env.BRANCH_NAME == "master") {
                    sh """
                    echo "This is a successfull pipeline"
                    """
                }
            }
        }
    }
}