pipeline {
    agent {
        node {
            label "terraform"
        }
    }

    environment {
        REMOTE_URL="${env.GIT_URL}" 
    }

    stages {
        // ********************************
        // *** Validate Terraform files ***
        // ********************************
        stage("Terraform Validate") {
            steps{
                echo "**** Validating ****"
                sh 'bash bin/validate.sh'
            }
        }

        // ****************************
        // *** Plan Terraform files ***
        // ****************************
        stage("Terraform Plan") {
            steps{
                echo "**** Planning ****"
                sh 'bash bin/plan.sh'
            }
        }

        // *****************************
        // *** Apply Terraform files ***
        // *****************************
        stage("Terraform Apply") {
            when {
                branch "staging"
            }
            steps{
                echo "**** Apply ****"
                sh 'bash bin/apply.sh'
            }
        }
    }

    post {
        success {
            script {
                if (env.BRANCH_NAME == "staging") {
                    withCredentials([string(credentialsId: 'themisAnagno_github_token', variable: 'TOKEN')]) {
                        sh '''
                        echo $REMOTE_URL
                        export GIT_ORG="$(echo $REMOTE_URL | cut -f4 -d'/')"
                        export GIT_REPO="$(echo $REMOTE_URL | cut -f5 -d'/')"
                        echo "${GIT_ORG}/${GIT_REPO}"
                        git status
                        git checkout master
                        git merge origin/staging
                        git push "https://themisAnagno:${TOKEN}@github.com/${GIT_ORG}/${GIT_REPO}"
                        '''
                    }
                }
            }
        }
    }
}